### ISSUE TITLE
NA from compute metric

### ISSUE THREAD

**Issue by denadai2** [PhilChodrow/compx#2]
Hello Phil,
I'm trying to follow your [vignette](https://philchodrow.github.io/compx/vignette_metric.html) to compute a measure of spatial segregation from your code.

Thus, I have my own map (shapefile in meter projection) and my own data. Unfortunately, I can't see where the problem lies but compute metric returns me NA without warnings:

    library(compx)
    library(tidyverse)    # data import, manipulation, and viz. Need dev version of ggplot2 for viz
    library(maptools)     # plot the tracts
    library(RColorBrewer) # for plots
    library(ggthemes)     # for theme_map
    library(viridis)      # for color scales
    library(units)        # needed by sf
    library(sf)           # for io and viz
    library(scales)       # for ggplot2 viz

    detroit_tracts <- st_read("data/shps/milano_int.shp")
    detroit_tracts %>% 
        ggplot() + 
        geom_sf() + 
        theme_map()

    detroit_race <- read_csv('data/prova.csv')
    detroit_race$n <- detroit_race$n
    head(detroit_race)

![screen shot 2018-05-29 at 19 10 05](https://user-images.githubusercontent.com/190799/40674074-0921362e-6374-11e8-83f6-69af22735644.png)

    tracts_to_use <- detroit_race 
    
    tracts <- detroit_tracts %>% 
        filter(GEOID %in% tracts_to_use$tract)
    
    data  <- tracts_to_use %>%
        filter(tract %in% tracts$GEOID) %>%
        group_by(tract) %>%
        ungroup() 
    
    metric_df <- compute_metric(tracts, 
                                data, 
                                km = T,
                                r_sigma = 10,
                                s_sigma = 1, 
                                smooth = F,
                                hessian = euc_)
    metric_df %>% head()

![screen shot 2018-05-29 at 19 09 42](https://user-images.githubusercontent.com/190799/40674095-1913d3f2-6374-11e8-8900-baeb36eb92c7.png)

Is it normal?

I used the same variables of the vignette to make a toy example :) 
Files are here (in case you need):
[data.zip](https://github.com/PhilChodrow/compx/files/2049670/data.zip)

I just installed R + packages (for the versions)

Thanks in advance

**Comment by denadai2** [comment]
I tried to debug the package. The result is created in the do_regression's try-catch. If I remove it I have:

    Error in mutate_impl(.data, dots): Evaluation error: Lapack routine dgesv: system is exactly singular: U[1,1] = 0.

**Comment by PhilChodrow** [comment]
Successfully reproduced error on my machine.

**Comment by PhilChodrow** [comment]
Hi Marco, 

It's a bit surprising, but the problem was actually the projection format of your data. I have added an error message to compute_metric that the algorithms expect longitude-latitude formatted data. The following code should now produce the attached figure. Please check that it does so and I'll close the issue. 

```
library(compx)
library(tidyverse)    # data import, manipulation, and viz. Need dev version of ggplot2 for viz
library(maptools)     # plot the tracts
library(RColorBrewer) # for plots
library(ggthemes)     # for theme_map
library(viridis)      # for color scales
library(units)        # needed by sf
library(sf)           # for io and viz
library(scales)       # for ggplot2 viz

detroit_tracts <- st_read("data/shps/milano_int.shp")
detroit_tracts <- st_transform(detroit_tracts, 4326) # comment this out to view new error message

detroit_tracts %>%
	ggplot() +
	geom_sf() +
	theme_map()

detroit_race <- read_csv('data/prova.csv')
detroit_race$n <- detroit_race$n
head(detroit_race)

tracts_to_use <- detroit_race

tracts <- detroit_tracts %>%
	filter(GEOID %in% tracts_to_use$tract)

data  <- tracts_to_use %>%
	filter(tract %in% tracts$GEOID) %>%
	group_by(tract) %>%
	ungroup()

# test
data <- data %>%
	group_by(tract, group) %>%
	summarise(n = sum(n)) %>%
	ungroup()

metric_df <- compute_metric(tracts,
							data,
							km = T,
							r_sigma = 10,
							s_sigma = 1,
							smooth = F,
							hessian = euc_)

metric_df <- metric_df %>%
	mutate(trace = map_dbl(g, . %>% diag() %>% sum()),
		   det   = map_dbl(g, . %>% det() %>% abs() %>% sqrt()))
metric_df %>% head()

tracts %>%
	left_join(metric_df, by = c('GEOID' = 'geoid')) %>%
	ggplot() +
	geom_sf(aes(fill = trace), size = .1) +
	viridis::scale_fill_viridis(trans = 'log10') +
	ggthemes::theme_map() +
	theme(legend.position = c(.8, .1)) +
	guides(fill = guide_colorbar(title = expression(italic(j[x]))))

ggsave('test.pdf')
```




[test.pdf](https://github.com/PhilChodrow/compx/files/2063264/test.pdf)

**Comment by denadai2** [comment]
Thank you! Now it works. Sorry but I was confused by the parameter "km", so I used a metric projection.

:)
