### ISSUE TITLE
vector memory exhausted

### ISSUE THREAD

**Issue by denadai2** [PhilChodrow/compx#3]
Hello Phil,
sorry for this. I found a possible error in the library.

With the same data sources as #2, I run:

	library(compx)        # main analysis functions
	library(tidyverse)    # for data manipulation and viz
	library(igraph)       # for network analysis
	library(RColorBrewer) # for plots
	library(ggthemes)     # for theme_map
	library(units)        # needed for sf
	library(sf)           # needed for io and visualization in this vignette
	library(scales)       # for ggplot2 viz
	library(RSpectra)     # fast eigenvalues, also used within compx

	detroit_tracts <- st_read("data/shps/milano_int.shp")
	detroit_tracts <- st_transform(detroit_tracts, 4326)

	race_2010 <- read_csv('data/prova.csv')
	race_2010$n <- race_2010$n
	
	tracts_to_use <- race_2010 

	tracts <- detroit_tracts %>% 
	    filter(GEOID %in% tracts_to_use$tract)

	js_dist <- function(n,m){
	    
	    N <- sum(n)
	    M <- sum(m)
	    
	    p <- n/N
	    q <- m/M
	    
	    sqrt((N/(M+N))*DKL(p, p+q) + (M/(M+N))*DKL(q, p+q))
	}

	g <- construct_information_graph(tracts = tracts, 
	                                 data = race_2010, 
	                                 divergence = js_dist)
	g

And the error is:

	Error: vector memory exhausted (limit reached?)
	Traceback:

	1. construct_information_graph(tracts = tracts, data = race_2010, 
	 .     divergence = js_dist)
	2. adj %>% undirect() %>% add_data(data_df) %>% information_distances(divergence) %>% 
	 .     make_graph() %>% add_n(data_df) %>% add_coordinates(tracts)
	3. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
	4. eval(quote(`_fseq`(`_lhs`)), env, env)
	5. eval(quote(`_fseq`(`_lhs`)), env, env)
	6. `_fseq`(`_lhs`)
	7. freduce(value, `_function_list`)
	8. function_list[[i]](value)
	9. add_n(., data_df)
	10. h %>% igraph::set.vertex.attribute("n", index = lookup$key, value = lookup$n)
	11. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
	12. eval(quote(`_fseq`(`_lhs`)), env, env)
	13. eval(quote(`_fseq`(`_lhs`)), env, env)
	14. `_fseq`(`_lhs`)
	15. freduce(value, `_function_list`)
	16. withVisible(function_list[[k]](value))
	17. function_list[[k]](value)
	18. igraph::set.vertex.attribute(., "n", index = lookup$key, value = lookup$n)
	19. i_set_vertex_attr(graph = graph, name = name, index = index, 
	  .     value = value)

The error lies in https://github.com/PhilChodrow/compx/blob/4f5c6fec88a21bb724343fe28cbe5d2bd13d852d/R/constructors.R#L180, because if I substitute this line with:

    h$name <- lookup$n

Everything works. I use the last version of R and Mac OS :(

**Comment by PhilChodrow** [comment]
Hmmm. When you say that everything works, do you mean that the `construct_information_graph()` call successfully resolves? Or that subsequent analysis functions also work as expected? I would expect (have not tested yet) that your fix would allow the former but that subsequent analyses would break.

**Comment by denadai2** [comment]
"everything" meaning that it is executed. I'm not enough expert in igraph to say my line works always the same as yours. However, the problem is raised also here:

https://github.com/PhilChodrow/compx/blob/4f5c6fec88a21bb724343fe28cbe5d2bd13d852d/R/constructors.R#L195

and whenever this function is called. Do you have the same problem?

**Comment by denadai2** [comment]
Ok, I found the error: GEOID/tract has to be a column of characters (not an integer).

It might be useful to know :))

**Comment by PhilChodrow** [comment]
Thank you for working this out Marco! I have added error messages for this using basic assert_that statements. I'm going to close out the issue. I'd love to hear if you have any suggestions on error handling or anything else. =)

**Comment by denadai2** [comment]
Unfortunately, I am a Pythonist :P
